# ===== ci(test/e2e) ======
name: End-to-End Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  e2e:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: 🛎 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to ensure the 'main' branch is available

      - name: Fetch main branch # Will be used for test splitting later
        run: git fetch origin main # Explicitly fetch the 'main' branch to ensure it's available

      - name: Install dependencies
        run: pnpm i

      - name: Run End-to-End tests
        env:
          SENTIO_API_KEY: ${{ secrets.SENTIO_API_KEY }}
        run: pnpm nx e2e web-e2e --verbose
